language: php

branches:
  only:
    - master
    - /^(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$/

services:
  - mysql

cache:
  apt: true
  directories:
    - $HOME/.composer/cache/files

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  global:
    - COMPOSER_NO_INTERACTION=1
  matrix:
    - WP_VERSION=nightly
    - WP_VERSION=latest
    - WP_VERSION=4.9.4

matrix:
  include:
    - php: '7.1'
      env: WP_VERSION=latest WITH_COVERAGE=true WITH_COVERAGE=true
  allow_failures:
    - php: nightly
    - env: WP_VERSION=nightly
  fast_finish: true

before_install:
  - $WITH_COVERAGE || phpenv config-rm xdebug.ini || true

  # Install helper scripts
  - travis_retry composer global require --prefer-dist --no-suggest typisttech/travis-nginx-wordpress
  - export PATH=$HOME/.composer/vendor/bin:$PATH
  - tnw-install-wordpress

  # Build the demo plugin
  - travis_retry composer build

  # Activate the plugin
  - wp plugin install ./release/wp-tabbed-admin-pages.zip --force --activate --path=/tmp/wordpress
  # Export a dump of plugin-activated database to the _data folder
  - wp db export $TRAVIS_BUILD_DIR/tests/_data/dump.sql --path=/tmp/wordpress

install:
  - travis_retry composer install --prefer-dist --no-suggest

script:
  - if [[ "$WITH_COVERAGE" == true ]]; then composer test:coverage; fi
  - if [[ "$WITH_COVERAGE" != true ]]; then composer test; fi

after_script:
  - if [[ "$WITH_COVERAGE" == true ]]; then travis_retry tnw-upload-coverage-to-scrutinizer; fi
  - if [[ "$WITH_COVERAGE" == true ]]; then travis_retry tnw-upload-coverage-to-codecov; fi
